Add builds for mac and linux
TheMoonrise/autonome-systeme pull request #3
Opened 2021-06-09 11:41 UTC by severinschmid

Mac is already tested, linux has to be tested on slurm cluster

2021-06-09 12:45 UTC, TheMoonrise requested changes

2021-06-09 12:45 UTC, TheMoonrise commented on unity/Crawler/ProjectSettings/ProjectSettings.asset
> +  runInBackground: 0
Why did you disable 'run in background'. Does this mean that the unity window must always have focus, because that would be very annoying.

2021-06-09 12:45 UTC, TheMoonrise commented on unity/Crawler/Assets/ML-Agents/Timers/Crawler_timers.json
> +{"count":1,"self":3.4075887999999996,"total":3.729787,"children":{"InitializeActuators":{"count":10,"self":0.002451,"total":0.002451,"children":null},"InitializeSensors":{"count":10,"self":0.01022599
Don't know what this does but I seems to get changed frequently. Maybe this can be added to .gitignore to avoid conflicts or what do you think?

2021-06-11 07:18 UTC, antoniahalbig approved these changes

2021-06-11 11:01 UTC, TheMoonrise commented on unity/Crawler/Assets/ML-Agents/Timers/Crawler_timers.json
> +{"count":1,"self":3.4075887999999996,"total":3.729787,"children":{"InitializeActuators":{"count":10,"self":0.002451,"total":0.002451,"children":null},"InitializeSensors":{"count":10,"self":0.01022599
Haha, the idea of conversations is not to just resolve them without making any changes^^ But I added the gitignore changes in my wrapper pull request, so this is actually resolved.

2021-06-11 11:01 UTC, TheMoonrise approved these changes

2021-06-11 11:04 UTC, merged