Feature sac
TheMoonrise/autonome-systeme pull request #4
Opened 2021-06-09 21:14 UTC by Mariiiam

Implementation of the Soft Actor Critic Algorithm.

2021-06-10 14:01 UTC, TheMoonrise requested changes

2021-06-10 14:01 UTC, TheMoonrise commented on main/src/sac/sac_actor_critic.py
> +device   = torch.device("cuda" if use_cuda else "cpu")
This is a duplicate. You have the same code in the training and play scripts already. I see that you push some tensors to `device` inside the models. Maybe you can consider to add the device as a parameter into the model. Otherwise, if you want to target a specific device you must change the code in multiple places.

2021-06-11 08:23 UTC, Mariiiam commented on main/example_sac_train_pendulum.py
> +Path("models/").mkdir(parents=True, exist_ok=True)
Thanks for the hint, we implemented your suggestion.

2021-06-11 08:28 UTC, Mariiiam commented on main/example_sac_train_pendulum.py
> +
We will try to avoid this in the future :)

2021-06-11 08:29 UTC, Mariiiam commented on main/example_sac_train_pendulum.py
> +from tensorboardX import SummaryWriter
We copied this from the tutorial. But now we used the same approach as you, Team A.

2021-06-11 08:31 UTC, Mariiiam commented on main/sac_train.sbatch
> +python3 -u example_sac_train_pendulum.py
Done 👍🏽

2021-06-11 08:34 UTC, Mariiiam commented on main/src/sac/sac_actor_critic.py
> +        return x
We will think about this but for now we leave it like this because it has not a high priority.

2021-06-11 08:35 UTC, Mariiiam commented on main/src/sac/sac_actor_critic.py
> +        return x
Does this have influence on the performance or is it just about the structure and code style?

2021-06-11 08:42 UTC, Mariiiam commented on main/src/sac/sac_actor_critic.py
> +device   = torch.device("cuda" if use_cuda else "cpu")
Thanks, we now have another solution to avoid the duplicate.

2021-06-11 09:29 UTC, Mariiiam commented on main/example_sac_train_pendulum.py
> +policy_lr = 3e-4
Thanks for the hint. We changed it.

2021-06-11 11:09 UTC, TheMoonrise commented on main/src/sac/sac_actor_critic.py
> +        return x
Honestly, no idea. But if I had to guess I would say it does not worsen the performance. I think this is just someting "newish" because in newer tutorials I usually find `nn.Sequential` while while the older ones do all the computation steps on their own. So yeah, probably only a question of style and having less code.

2021-06-11 11:14 UTC, TheMoonrise requested changes

2021-06-11 11:14 UTC, TheMoonrise commented on .gitignore
> +models/
sorry to bring this up again. I think we had a missunderstanding 😅 
I was talking about the `models/` rule and that it would be great if you could remove it, not the `\runs`. I probably selected the wrong line for the comment. By the way, did you know you can add emoji using the :smiile: notation? 👍🏾 🤖 🔥

2021-06-14 12:35 UTC, VerenaWinterhalter commented on .gitignore
> +models/
👍

2021-06-15 11:41 UTC, TheMoonrise requested changes
I added two more comments. One regarding some files which should not be committed and the other on changes to the unity project. I think it is a good idea that this branch get's merged. So maybe you can have a look at them, merge the main branch, run the pipeline and then mark this pull request as ready for review.

2021-06-15 11:41 UTC, TheMoonrise commented on .idea/.gitignore
> +/httpRequests/
This looks like files from a specific ide. You should add the .idea folder to the `.gitignore` and remove all the files that are already tracked, because these files probably are only relevant for you.

2021-06-15 11:41 UTC, TheMoonrise commented on unity/Crawler/Packages/manifest.json
> +    "com.unity.ml-agents.extensions": "file:C:/Users/veren/Downloads/ml-agents-main/ml-agents-main/com.unity.ml-agents.extensions",
There is a problem here where I initially imported the packages from my local directory which obviously does not work for anyone else. This is, however, already resolved on the main branch. All local imports are replaced with imports directly from git or the unity repositories so that they should work for everyone. Therefore, please undo these changes as otherwise the project will again be broken for everyone except you.

2021-06-16 10:50 UTC, TheMoonrise approved these changes

2021-06-17 07:27 UTC, VerenaWinterhalter approved these changes

2021-06-17 07:30 UTC, merged